name: inmoviva
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.8.0
  image_picker: ^1.0.0
  provider: ^6.0.4
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0
  url_launcher: ^6.1.5
  file_picker: ^5.2.3
  path_provider: ^2.0.10
  intl: ^0.17.0
  webview_flutter: ^4.0.0
  pdf: ^3.6.0
  printing: ^5.4.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
   - assets/utils/